spring:
  data.rest.basePath: /api/v1
  zipkin.baseUrl: http://localhost:9411

eureka:
  instance.preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka

logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      tesei7.ms: DEBUG